name: Tests E2E
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    types: [ opened, reopened ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    if: ${{ github.actor != 'dependabot[bot]' }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ ubuntu-latest, macos-latest ]
        nodejs: [ 16 ]
        contract: [ js, rust ]
        frontend: [ none ]
        tests: [ js, rust ]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.nodejs }}
      - name: Prepare
        run: |
          mkdir -p ~/.near-config
          echo "{\"trackingEnabled\": false,\"trackingAccountID\": false}" >| ~/.near-config/settings.json
      - name: Install modules
        run: |
          npm install
          npm run build
      - name: Scaffold template
        run: |
          node index.js _testrun --contract ${{ matrix.contract }} --frontend ${{ matrix.frontend }} --tests ${{ matrix.tests }} --install
      - name: Build template
        env:
          NEAR_ENV: ci
          IS_GITHUB_ACTION: true
        run: |
          cd _testrun
          npm run build
      - name: Test template
        env:
          NEAR_ENV: ci
          IS_GITHUB_ACTION: true
        run: |
          cd _testrun
          npm run test